{
 "title": "Apache Kafka Broker Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "OS Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory (JVM & Physical)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvmMemory",
     "select": [
      [
       { "params": [ "init" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "heap" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "attributeName", "operator": "=", "value": "HeapMemoryUsage" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvmMemory",
     "select": [
      [
       { "params": [ "init" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "non-heap" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "attributeName", "operator": "=", "value": "NonHeapMemoryUsage" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "os",
     "select": [
      [
       { "params": [ "FreePhysicalMemorySize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "physical" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "os",
     "select": [
      [
       { "params": [ "ProcessCpuLoad" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "process" ], "type": "alias" }
      ],
      [
       { "params": [ "SystemCpuLoad" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "SystemLoadAverage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "loadAvg" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Critical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Log Flush latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LogFlush",
     "select": [
      [
       { "params": [ "98thPercentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UnderReplicatedPartitions",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Messages In per sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MessagesInPerSec",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MessagesInPerSecPerTopic",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t1" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=MessagesInPerSec,topic=t1"
      }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MessagesInPerSecPerTopic",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t2" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=MessagesInPerSec,topic=t2"
      }
     ]
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesInPerSec",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesInPerSecPerTopic",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t1" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesInPerSec,topic=t1"
      }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesInPerSecPerTopic",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t2" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesInPerSec,topic=t2"
      }
     ]
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesOutPerSec",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesOutPerSecPerTopic",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t1" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesOutPerSec,topic=t1"
      }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesOutPerSecPerTopic",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t2" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesOutPerSec,topic=t2"
      }
     ]
    }
   ]
  },
  {
   "title": "Bytes In (5 minute rate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesInPerSec",
     "select": [
      [
       { "params": [ "FiveMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesInPerSecPerTopic",
     "select": [
      [
       { "params": [ "FiveMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t1" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesInPerSec,topic=t1"
      }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesInPerSecPerTopic",
     "select": [
      [
       { "params": [ "FiveMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t2" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesInPerSec,topic=t2"
      }
     ]
    }
   ]
  },
  {
   "title": "Bytes Out (5 minute rate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesOutPerSec",
     "select": [
      [
       { "params": [ "FiveMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesOutPerSecPerTopic",
     "select": [
      [
       { "params": [ "FiveMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t1" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesOutPerSec,topic=t1"
      }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesOutPerSecPerTopic",
     "select": [
      [
       { "params": [ "FiveMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t2" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesOutPerSec,topic=t2"
      }
     ]
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Partition / Leader Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionCount",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LeaderCount",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OfflinePartitionsCount",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Handler avg idle",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RequestHandlerAvgIdlePercent",
     "select": [
      [
       { "params": [ "MeanRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Leader Election",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LeaderElectionRateAndTimeMs",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UncleanLeaderElectionsPerSec",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ActiveControllerCount",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Network Processor avg idle",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NetworkProcessorAvgIdlePercent ",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests 1 minute rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ProduceRequestsPerSec",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FetchConsumerRequestsPerSec",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FetchFollowerRequestsPerSec",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests Total Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ProduceTotalTimeMs",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FetchConsumerTotalTimeMs",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FetchFollowerTotalTimeMs",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Queue Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ProduceRequestQueueTimeMs",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FetchConsumerRequestQueueTimeMs",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FetchFollowerRequestQueueTimeMs",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}