version: '2'
volumes:
    broker-data:
    broker-secrets:
services:
    kafka:
        image: apache/kafka:3.9.1
        container_name: broker
        hostname: broker
        ports:
            - 9092:9092
            - 9080:8080
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: PLAINTEXT://broker:9092,CONTROLLER://broker:9093
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_CREATE_TOPICS: "Stocks:2:1,Quotes:2:1,Orders:2:1"
        volumes:
        - type: volume
          source: broker-data
          target: /var/lib/kafka/data
        - type: volume
          source: broker-secrets
          target: /etc/kafka/secrets
   
    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui
        ports:
            - "8080:8080"
        environment:
            DYNAMIC_CONFIG_ENABLED: 'true'
            KAFKA_CLUSTERS_0_NAME: kafkacluster
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker:9092,localhost:9092'
    influxdb:
        image: influxdb:1.8
        ports:
            - "8086:8086"
        environment:
            - INFLUXDB_DB=k6
    grafana:
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        environment:
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_BASIC_ENABLED=false
        volumes:
            - ./grafana:/etc/grafana/provisioning/
    k6:
        image: grafana/k6:latest
        ports:
             - "6566:6565"
        environment:
             - K6_OUT=influxdb=http://influxdb:8086/k6
        volumes:
             - ./samples:/scripts
    k6-kafka:
        image: mostafamoradian/xk6-kafka:latest
        ports:
             - "6565:6565"
        environment:
             - K6_OUT=influxdb=http://influxdb:8086/k6kafka
        volumes:
             - ./samples-k6kafka:/scripts
