version: '2'
volumes:
    broker-data: 
    broker-secrets: 
    broker-data2:
    broker-secrets2: 
    broker-data3: 
    broker-secrets3: 
services:
    kafka:
        image: apache/kafka:3.9.1
        container_name: broker
        hostname: broker
        ports:
            - 9092:9092
            - 9093:9093
            - 5555:5555
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_BROKER_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: PLAINTEXT://broker:9092,CONTROLLER://broker:9093
            KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:9092,CONTROLLER://broker:9093'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:9093,2@broker2:9093,3@broker3:9093'
            KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
            CLUSTER_ID: 'MY_CLUCSETER_SWAM-QESM_ID'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_DEFAULT_REPLICATION_FACTOR: 3
            KAFKA_MIN_INSYNC_REPLICAS: 2
            KAFKA_JMX_PORT: 5555
            KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.rmi.port=5555 -Dcom.sun.management.jmxremote.port=5555"
        volumes:
        - type: volume
          source: broker-data
          target: /var/lib/kafka/data
        - type: volume
          source: broker-secrets
          target: /etc/kafka/secrets
    kafka2:
        image: apache/kafka:3.9.1
        container_name: broker2
        hostname: broker2
        ports:
            - 9094:9092
            - 9095:9093
            - 6666:6666
        environment:
            KAFKA_NODE_ID: 2
            KAFKA_BROKER_ID: 2
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: PLAINTEXT://broker2:9092,CONTROLLER://broker2:9093
            KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker2:9092,CONTROLLER://broker2:9093'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:9093,2@broker2:9093,3@broker3:9093'
            KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
            CLUSTER_ID: 'MY_CLUCSETER_SWAM-QESM_ID'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_DEFAULT_REPLICATION_FACTOR: 3
            KAFKA_MIN_INSYNC_REPLICAS: 2
            KAFKA_JMX_PORT: 6666
            KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.rmi.port=6666 -Dcom.sun.management.jmxremote.port=6666"

        volumes:
        - type: volume
          source: broker-data2
          target: /var/lib/kafka/data
        - type: volume
          source: broker-secrets2
          target: /etc/kafka/secrets

    kafka3:
        image: apache/kafka:3.9.1
        container_name: broker3
        hostname: broker3
        ports:
            - 9096:9092
            - 9097:9093
            - 7777:7777
        environment:
            KAFKA_NODE_ID: 3
            KAFKA_BROKER_ID: 3
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: PLAINTEXT://broker3:9092,CONTROLLER://broker3:9093
            KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker3:9092,CONTROLLER://broker3:9093'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:9093,2@broker2:9093,3@broker3:9093'
            KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
            CLUSTER_ID: 'MY_CLUCSETER_SWAM-QESM_ID'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_DEFAULT_REPLICATION_FACTOR: 3
            KAFKA_MIN_INSYNC_REPLICAS: 2
            KAFKA_JMX_PORT: 7777
            KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.rmi.port=7777 -Dcom.sun.management.jmxremote.port=7777"

        volumes:
        - type: volume
          source: broker-data3
          target: /var/lib/kafka/data
        - type: volume
          source: broker-secrets3
          target: /etc/kafka/secrets 
    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui
        ports:
            - "8080:8080"
        environment:
            DYNAMIC_CONFIG_ENABLED: 'true'
            KAFKA_CLUSTERS_0_NAME: kafkacluster
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker:9092,broker2:9092,broker3:9092'
        depends_on:
            - kafka
            - kafka2
            - kafka3
    influxdb:
        image: influxdb:1.8
        ports:
            - "8086:8086"
        environment:
            - INFLUXDB_DB=k6kafka
    grafana:
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        environment:
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_BASIC_ENABLED=false
        volumes:
            - ./grafana:/etc/grafana/provisioning/
    k6-kafka:
        image: mostafamoradian/xk6-kafka:latest
        ports:
             - "6565:6565"
        environment:
             - K6_OUT=influxdb=http://influxdb:8086/k6kafka
        volumes:
             - ./samples-k6kafka:/scripts
    speedbump:
        image: kffl/speedbump:latest
        command: --latency=1000ms --sine-amplitude=1000ms --sine-period=1m --port=8000 kafka:9092
    speedbump2:
        image: kffl/speedbump:latest
        command: --latency=1000ms --sine-amplitude=1000ms --sine-period=1m --port=8002 kafka2:9092
    speedbump3:
        image: kffl/speedbump:latest
        command: --latency=1000ms --sine-amplitude=1000ms --sine-period=1m --port=8003 kafka3:9092
    jmxtrans:
        container_name: jmxtrans         
        image: jmxtrans/jmxtrans
        volumes: 
            - ./jmxtrans:/var/lib/jmxtrans
